
CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -g

all: final_main 

final_main: final_main.cpp 
	${CXX} ${CFLAGS} final_main.cpp -o final_main

clean: 
	rm -f final_main testProg *.o
