
CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -g

all: assign3_main

assign3_main: assign3_main.cpp 
	${CXX} ${CFLAGS} assign3_main.cpp -o assign3_main

clean: 
	rm -f assign3_main *.o
